### ISSUE TITLE
createList() not returning 5000 random numbers.

### ISSUE THREAD

**Issue by aking6083** [aking6083/kingTranAssn3#5]
When I run through the random number array there are a bunch of 0 or empty slots, and the array only counts to 4919.  I believe the sentinel search method in isDupe() is to blame.  I dont quite know

This is the loop I used to test..  
![image](https://cloud.githubusercontent.com/assets/3180395/5984116/08701cea-a8a1-11e4-8d8a-25ab540dff7d.png)

**Comment by ctran88** [comment]
I"ll take a look.

**Comment by ctran88** [comment]
I was not able to replicate your results.  With the current TranTesting branch and the following test code that you can see in my main() function, I came up with what is printed on the console.  While I was watching it print from index 0-4999, I did not see any noticeable list of zero values.

![image](https://cloud.githubusercontent.com/assets/10686030/5985663/c541ebe2-a8aa-11e4-8d17-09ddd24070ee.png)

**Comment by aking6083** [comment]
I must have an old version, can you push your latest changes???  I couldn't
get it to work with my chain hash.

AK

**Comment by ctran88** [comment]
I just merged TranTesting with master.  Master should now be up-to-date.

**Comment by ctran88** [comment]
Oh, whenever you get a chance, please see my comments on my function, showResults().  Having trouble figuring out how to code it..
